run a config check before start, reload, restart ant exit if the config is broken

diff --git a/specs/nagios/daemon-init-redhat.in b/specs/nagios/daemon-init-redhat.in
--- a/specs/nagios/daemon-init-redhat.in
+++ b/specs/nagios/daemon-init-redhat.in
@@ -68,9 +68,23 @@ force_reload() {
     restart
 }
 
+check_config() {
+        $nice runuser -s /bin/bash - $user -c "$corelimit >/dev/null 2>&1 ; $exec -v $config > /dev/null 2>&1"
+        RETVAL=$?
+        if [ $RETVAL -ne 0 ] ; then
+                echo -n $"Configuration validation failed"
+                failure
+                echo
+                exit 1
+
+        fi
+}
+
+
 case "$1" in
     start)
         status $prog && exit 0
+	check_config
         $1
         ;;
     stop)
@@ -78,13 +92,16 @@ case "$1" in
         $1
         ;;
     restart)
+	check_config
         $1
         ;;
     reload)
         status $prog || exit 7
+	check_config
         $1
         ;;
     force-reload)
+	check_config
         force_reload
         ;;
     status)
@@ -92,11 +109,13 @@ case "$1" in
         ;;
     condrestart|try-restart)
         status $prog|| exit 0
+	check_config
         restart
         ;;
     configtest)
- 	$nice runuser -s /bin/bash - $user -c "$corelimit >/dev/null 2>&1 ; $exec -v $config"
-	RETVAL=$?
+        echo -n  $"Checking config for $prog: "
+        check_config && success
+        echo
 	;;
     *)
         echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload|configtest}"
